# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from voronoi_cbsa/ExchangeDataArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg
import voronoi_cbsa.msg

class ExchangeDataArray(genpy.Message):
  _md5sum = "123206d5e1536f22170e5c5739052f99"
  _type = "voronoi_cbsa/ExchangeDataArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """ExchangeData[] data
================================================================================
MSG: voronoi_cbsa/ExchangeData
int64               id
geometry_msgs/Point position
SensorArray         role
WeightArray         weights
WeightArray         sensor_scores
float64             operation_range
float64             approx_param
float64             smoke_variance
float64             camera_range
float64             angle_of_view
float64             camera_variance
std_msgs/Float64MultiArray vel_cmd

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: voronoi_cbsa/SensorArray
Sensor[] sensors
================================================================================
MSG: voronoi_cbsa/Sensor
string type
float64 score
================================================================================
MSG: voronoi_cbsa/WeightArray
Weight[] weights
================================================================================
MSG: voronoi_cbsa/Weight
string  type
int16   event_id
float64 score
================================================================================
MSG: std_msgs/Float64MultiArray
# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
float64[]         data          # array of data


================================================================================
MSG: std_msgs/MultiArrayLayout
# The multiarray declares a generic multi-dimensional array of a
# particular data type.  Dimensions are ordered from outer most
# to inner most.

MultiArrayDimension[] dim # Array of dimension properties
uint32 data_offset        # padding elements at front of data

# Accessors should ALWAYS be written in terms of dimension stride
# and specified outer-most dimension first.
# 
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]
#
# A standard, 3-channel 640x480 image with interleaved color channels
# would be specified as:
#
# dim[0].label  = "height"
# dim[0].size   = 480
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)
# dim[1].label  = "width"
# dim[1].size   = 640
# dim[1].stride = 3*640 = 1920
# dim[2].label  = "channel"
# dim[2].size   = 3
# dim[2].stride = 3
#
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.

================================================================================
MSG: std_msgs/MultiArrayDimension
string label   # label of given dimension
uint32 size    # size of given dimension (in type units)
uint32 stride  # stride of given dimension"""
  __slots__ = ['data']
  _slot_types = ['voronoi_cbsa/ExchangeData[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ExchangeDataArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.data is None:
        self.data = []
    else:
      self.data = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.data)
      buff.write(_struct_I.pack(length))
      for val1 in self.data:
        _x = val1.id
        buff.write(_get_struct_q().pack(_x))
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.role
        length = len(_v2.sensors)
        buff.write(_struct_I.pack(length))
        for val3 in _v2.sensors:
          _x = val3.type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val3.score
          buff.write(_get_struct_d().pack(_x))
        _v3 = val1.weights
        length = len(_v3.weights)
        buff.write(_struct_I.pack(length))
        for val3 in _v3.weights:
          _x = val3.type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val3
          buff.write(_get_struct_hd().pack(_x.event_id, _x.score))
        _v4 = val1.sensor_scores
        length = len(_v4.weights)
        buff.write(_struct_I.pack(length))
        for val3 in _v4.weights:
          _x = val3.type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val3
          buff.write(_get_struct_hd().pack(_x.event_id, _x.score))
        _x = val1
        buff.write(_get_struct_6d().pack(_x.operation_range, _x.approx_param, _x.smoke_variance, _x.camera_range, _x.angle_of_view, _x.camera_variance))
        _v5 = val1.vel_cmd
        _v6 = _v5.layout
        length = len(_v6.dim)
        buff.write(_struct_I.pack(length))
        for val4 in _v6.dim:
          _x = val4.label
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val4
          buff.write(_get_struct_2I().pack(_x.size, _x.stride))
        _x = _v6.data_offset
        buff.write(_get_struct_I().pack(_x))
        length = len(_v5.data)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.Struct(pattern).pack(*_v5.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.data is None:
        self.data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.data = []
      for i in range(0, length):
        val1 = voronoi_cbsa.msg.ExchangeData()
        start = end
        end += 8
        (val1.id,) = _get_struct_q().unpack(str[start:end])
        _v7 = val1.position
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.role
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v8.sensors = []
        for i in range(0, length):
          val3 = voronoi_cbsa.msg.Sensor()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val3.type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val3.type = str[start:end]
          start = end
          end += 8
          (val3.score,) = _get_struct_d().unpack(str[start:end])
          _v8.sensors.append(val3)
        _v9 = val1.weights
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v9.weights = []
        for i in range(0, length):
          val3 = voronoi_cbsa.msg.Weight()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val3.type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val3.type = str[start:end]
          _x = val3
          start = end
          end += 10
          (_x.event_id, _x.score,) = _get_struct_hd().unpack(str[start:end])
          _v9.weights.append(val3)
        _v10 = val1.sensor_scores
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v10.weights = []
        for i in range(0, length):
          val3 = voronoi_cbsa.msg.Weight()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val3.type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val3.type = str[start:end]
          _x = val3
          start = end
          end += 10
          (_x.event_id, _x.score,) = _get_struct_hd().unpack(str[start:end])
          _v10.weights.append(val3)
        _x = val1
        start = end
        end += 48
        (_x.operation_range, _x.approx_param, _x.smoke_variance, _x.camera_range, _x.angle_of_view, _x.camera_variance,) = _get_struct_6d().unpack(str[start:end])
        _v11 = val1.vel_cmd
        _v12 = _v11.layout
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v12.dim = []
        for i in range(0, length):
          val4 = std_msgs.msg.MultiArrayDimension()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val4.label = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val4.label = str[start:end]
          _x = val4
          start = end
          end += 8
          (_x.size, _x.stride,) = _get_struct_2I().unpack(str[start:end])
          _v12.dim.append(val4)
        start = end
        end += 4
        (_v12.data_offset,) = _get_struct_I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        _v11.data = s.unpack(str[start:end])
        self.data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.data)
      buff.write(_struct_I.pack(length))
      for val1 in self.data:
        _x = val1.id
        buff.write(_get_struct_q().pack(_x))
        _v13 = val1.position
        _x = _v13
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v14 = val1.role
        length = len(_v14.sensors)
        buff.write(_struct_I.pack(length))
        for val3 in _v14.sensors:
          _x = val3.type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val3.score
          buff.write(_get_struct_d().pack(_x))
        _v15 = val1.weights
        length = len(_v15.weights)
        buff.write(_struct_I.pack(length))
        for val3 in _v15.weights:
          _x = val3.type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val3
          buff.write(_get_struct_hd().pack(_x.event_id, _x.score))
        _v16 = val1.sensor_scores
        length = len(_v16.weights)
        buff.write(_struct_I.pack(length))
        for val3 in _v16.weights:
          _x = val3.type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val3
          buff.write(_get_struct_hd().pack(_x.event_id, _x.score))
        _x = val1
        buff.write(_get_struct_6d().pack(_x.operation_range, _x.approx_param, _x.smoke_variance, _x.camera_range, _x.angle_of_view, _x.camera_variance))
        _v17 = val1.vel_cmd
        _v18 = _v17.layout
        length = len(_v18.dim)
        buff.write(_struct_I.pack(length))
        for val4 in _v18.dim:
          _x = val4.label
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val4
          buff.write(_get_struct_2I().pack(_x.size, _x.stride))
        _x = _v18.data_offset
        buff.write(_get_struct_I().pack(_x))
        length = len(_v17.data)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(_v17.data.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.data is None:
        self.data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.data = []
      for i in range(0, length):
        val1 = voronoi_cbsa.msg.ExchangeData()
        start = end
        end += 8
        (val1.id,) = _get_struct_q().unpack(str[start:end])
        _v19 = val1.position
        _x = _v19
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v20 = val1.role
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v20.sensors = []
        for i in range(0, length):
          val3 = voronoi_cbsa.msg.Sensor()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val3.type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val3.type = str[start:end]
          start = end
          end += 8
          (val3.score,) = _get_struct_d().unpack(str[start:end])
          _v20.sensors.append(val3)
        _v21 = val1.weights
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v21.weights = []
        for i in range(0, length):
          val3 = voronoi_cbsa.msg.Weight()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val3.type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val3.type = str[start:end]
          _x = val3
          start = end
          end += 10
          (_x.event_id, _x.score,) = _get_struct_hd().unpack(str[start:end])
          _v21.weights.append(val3)
        _v22 = val1.sensor_scores
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v22.weights = []
        for i in range(0, length):
          val3 = voronoi_cbsa.msg.Weight()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val3.type = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val3.type = str[start:end]
          _x = val3
          start = end
          end += 10
          (_x.event_id, _x.score,) = _get_struct_hd().unpack(str[start:end])
          _v22.weights.append(val3)
        _x = val1
        start = end
        end += 48
        (_x.operation_range, _x.approx_param, _x.smoke_variance, _x.camera_range, _x.angle_of_view, _x.camera_variance,) = _get_struct_6d().unpack(str[start:end])
        _v23 = val1.vel_cmd
        _v24 = _v23.layout
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v24.dim = []
        for i in range(0, length):
          val4 = std_msgs.msg.MultiArrayDimension()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val4.label = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val4.label = str[start:end]
          _x = val4
          start = end
          end += 8
          (_x.size, _x.stride,) = _get_struct_2I().unpack(str[start:end])
          _v24.dim.append(val4)
        start = end
        end += 4
        (_v24.data_offset,) = _get_struct_I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        _v23.data = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        self.data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_hd = None
def _get_struct_hd():
    global _struct_hd
    if _struct_hd is None:
        _struct_hd = struct.Struct("<hd")
    return _struct_hd
_struct_q = None
def _get_struct_q():
    global _struct_q
    if _struct_q is None:
        _struct_q = struct.Struct("<q")
    return _struct_q
