# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from voronoi_cbsa/ExchangeData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import voronoi_cbsa.msg

class ExchangeData(genpy.Message):
  _md5sum = "2f42667d1e0a184c7cc115f894849626"
  _type = "voronoi_cbsa/ExchangeData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64               id
geometry_msgs/Point position
SensorArray         role
WeightArray         weights
WeightArray         sensor_scores
float64             operation_range
float64             approx_param
float64             smoke_variance
float64             camera_range
float64             angle_of_view
float64             camera_variance
geometry_msgs/Point velocity

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: voronoi_cbsa/SensorArray
Sensor[] sensors
================================================================================
MSG: voronoi_cbsa/Sensor
string type
float64 score
================================================================================
MSG: voronoi_cbsa/WeightArray
Weight[] weights
================================================================================
MSG: voronoi_cbsa/Weight
string  type
int16   event_id
float64 score"""
  __slots__ = ['id','position','role','weights','sensor_scores','operation_range','approx_param','smoke_variance','camera_range','angle_of_view','camera_variance','velocity']
  _slot_types = ['int64','geometry_msgs/Point','voronoi_cbsa/SensorArray','voronoi_cbsa/WeightArray','voronoi_cbsa/WeightArray','float64','float64','float64','float64','float64','float64','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,position,role,weights,sensor_scores,operation_range,approx_param,smoke_variance,camera_range,angle_of_view,camera_variance,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ExchangeData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.role is None:
        self.role = voronoi_cbsa.msg.SensorArray()
      if self.weights is None:
        self.weights = voronoi_cbsa.msg.WeightArray()
      if self.sensor_scores is None:
        self.sensor_scores = voronoi_cbsa.msg.WeightArray()
      if self.operation_range is None:
        self.operation_range = 0.
      if self.approx_param is None:
        self.approx_param = 0.
      if self.smoke_variance is None:
        self.smoke_variance = 0.
      if self.camera_range is None:
        self.camera_range = 0.
      if self.angle_of_view is None:
        self.angle_of_view = 0.
      if self.camera_variance is None:
        self.camera_variance = 0.
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Point()
    else:
      self.id = 0
      self.position = geometry_msgs.msg.Point()
      self.role = voronoi_cbsa.msg.SensorArray()
      self.weights = voronoi_cbsa.msg.WeightArray()
      self.sensor_scores = voronoi_cbsa.msg.WeightArray()
      self.operation_range = 0.
      self.approx_param = 0.
      self.smoke_variance = 0.
      self.camera_range = 0.
      self.angle_of_view = 0.
      self.camera_variance = 0.
      self.velocity = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q3d().pack(_x.id, _x.position.x, _x.position.y, _x.position.z))
      length = len(self.role.sensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.role.sensors:
        _x = val1.type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.score
        buff.write(_get_struct_d().pack(_x))
      length = len(self.weights.weights)
      buff.write(_struct_I.pack(length))
      for val1 in self.weights.weights:
        _x = val1.type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_hd().pack(_x.event_id, _x.score))
      length = len(self.sensor_scores.weights)
      buff.write(_struct_I.pack(length))
      for val1 in self.sensor_scores.weights:
        _x = val1.type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_hd().pack(_x.event_id, _x.score))
      _x = self
      buff.write(_get_struct_9d().pack(_x.operation_range, _x.approx_param, _x.smoke_variance, _x.camera_range, _x.angle_of_view, _x.camera_variance, _x.velocity.x, _x.velocity.y, _x.velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.role is None:
        self.role = voronoi_cbsa.msg.SensorArray()
      if self.weights is None:
        self.weights = voronoi_cbsa.msg.WeightArray()
      if self.sensor_scores is None:
        self.sensor_scores = voronoi_cbsa.msg.WeightArray()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.id, _x.position.x, _x.position.y, _x.position.z,) = _get_struct_q3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.role.sensors = []
      for i in range(0, length):
        val1 = voronoi_cbsa.msg.Sensor()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.type = str[start:end]
        start = end
        end += 8
        (val1.score,) = _get_struct_d().unpack(str[start:end])
        self.role.sensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.weights.weights = []
      for i in range(0, length):
        val1 = voronoi_cbsa.msg.Weight()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.type = str[start:end]
        _x = val1
        start = end
        end += 10
        (_x.event_id, _x.score,) = _get_struct_hd().unpack(str[start:end])
        self.weights.weights.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sensor_scores.weights = []
      for i in range(0, length):
        val1 = voronoi_cbsa.msg.Weight()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.type = str[start:end]
        _x = val1
        start = end
        end += 10
        (_x.event_id, _x.score,) = _get_struct_hd().unpack(str[start:end])
        self.sensor_scores.weights.append(val1)
      _x = self
      start = end
      end += 72
      (_x.operation_range, _x.approx_param, _x.smoke_variance, _x.camera_range, _x.angle_of_view, _x.camera_variance, _x.velocity.x, _x.velocity.y, _x.velocity.z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q3d().pack(_x.id, _x.position.x, _x.position.y, _x.position.z))
      length = len(self.role.sensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.role.sensors:
        _x = val1.type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.score
        buff.write(_get_struct_d().pack(_x))
      length = len(self.weights.weights)
      buff.write(_struct_I.pack(length))
      for val1 in self.weights.weights:
        _x = val1.type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_hd().pack(_x.event_id, _x.score))
      length = len(self.sensor_scores.weights)
      buff.write(_struct_I.pack(length))
      for val1 in self.sensor_scores.weights:
        _x = val1.type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_hd().pack(_x.event_id, _x.score))
      _x = self
      buff.write(_get_struct_9d().pack(_x.operation_range, _x.approx_param, _x.smoke_variance, _x.camera_range, _x.angle_of_view, _x.camera_variance, _x.velocity.x, _x.velocity.y, _x.velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.role is None:
        self.role = voronoi_cbsa.msg.SensorArray()
      if self.weights is None:
        self.weights = voronoi_cbsa.msg.WeightArray()
      if self.sensor_scores is None:
        self.sensor_scores = voronoi_cbsa.msg.WeightArray()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.id, _x.position.x, _x.position.y, _x.position.z,) = _get_struct_q3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.role.sensors = []
      for i in range(0, length):
        val1 = voronoi_cbsa.msg.Sensor()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.type = str[start:end]
        start = end
        end += 8
        (val1.score,) = _get_struct_d().unpack(str[start:end])
        self.role.sensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.weights.weights = []
      for i in range(0, length):
        val1 = voronoi_cbsa.msg.Weight()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.type = str[start:end]
        _x = val1
        start = end
        end += 10
        (_x.event_id, _x.score,) = _get_struct_hd().unpack(str[start:end])
        self.weights.weights.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sensor_scores.weights = []
      for i in range(0, length):
        val1 = voronoi_cbsa.msg.Weight()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.type = str[start:end]
        _x = val1
        start = end
        end += 10
        (_x.event_id, _x.score,) = _get_struct_hd().unpack(str[start:end])
        self.sensor_scores.weights.append(val1)
      _x = self
      start = end
      end += 72
      (_x.operation_range, _x.approx_param, _x.smoke_variance, _x.camera_range, _x.angle_of_view, _x.camera_variance, _x.velocity.x, _x.velocity.y, _x.velocity.z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_hd = None
def _get_struct_hd():
    global _struct_hd
    if _struct_hd is None:
        _struct_hd = struct.Struct("<hd")
    return _struct_hd
_struct_q3d = None
def _get_struct_q3d():
    global _struct_q3d
    if _struct_q3d is None:
        _struct_q3d = struct.Struct("<q3d")
    return _struct_q3d
