// Generated by gencpp from file state_estimation/EIFpairStamped.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATION_MESSAGE_EIFPAIRSTAMPED_H
#define STATE_ESTIMATION_MESSAGE_EIFPAIRSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace state_estimation
{
template <class ContainerAllocator>
struct EIFpairStamped_
{
  typedef EIFpairStamped_<ContainerAllocator> Type;

  EIFpairStamped_()
    : header()
    , stateSize(0)
    , id(0)
    , P_hat()
    , X_hat()
    , s()
    , y()  {
    }
  EIFpairStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , stateSize(0)
    , id(0)
    , P_hat(_alloc)
    , X_hat(_alloc)
    , s(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _stateSize_type;
  _stateSize_type stateSize;

   typedef int32_t _id_type;
  _id_type id;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _P_hat_type;
  _P_hat_type P_hat;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _X_hat_type;
  _X_hat_type X_hat;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _s_type;
  _s_type s;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::state_estimation::EIFpairStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimation::EIFpairStamped_<ContainerAllocator> const> ConstPtr;

}; // struct EIFpairStamped_

typedef ::state_estimation::EIFpairStamped_<std::allocator<void> > EIFpairStamped;

typedef boost::shared_ptr< ::state_estimation::EIFpairStamped > EIFpairStampedPtr;
typedef boost::shared_ptr< ::state_estimation::EIFpairStamped const> EIFpairStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimation::EIFpairStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimation::EIFpairStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimation::EIFpairStamped_<ContainerAllocator1> & lhs, const ::state_estimation::EIFpairStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.stateSize == rhs.stateSize &&
    lhs.id == rhs.id &&
    lhs.P_hat == rhs.P_hat &&
    lhs.X_hat == rhs.X_hat &&
    lhs.s == rhs.s &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimation::EIFpairStamped_<ContainerAllocator1> & lhs, const ::state_estimation::EIFpairStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimation::EIFpairStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimation::EIFpairStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimation::EIFpairStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimation::EIFpairStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimation::EIFpairStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimation::EIFpairStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimation::EIFpairStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26b414ae046293c626e824119402b4fd";
  }

  static const char* value(const ::state_estimation::EIFpairStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26b414ae046293c6ULL;
  static const uint64_t static_value2 = 0x26e824119402b4fdULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimation::EIFpairStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimation/EIFpairStamped";
  }

  static const char* value(const ::state_estimation::EIFpairStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimation::EIFpairStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 stateSize\n"
"int32 id\n"
"float64[] P_hat\n"
"float64[] X_hat\n"
"float64[] s\n"
"float64[] y\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::state_estimation::EIFpairStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimation::EIFpairStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.stateSize);
      stream.next(m.id);
      stream.next(m.P_hat);
      stream.next(m.X_hat);
      stream.next(m.s);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EIFpairStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimation::EIFpairStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimation::EIFpairStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "stateSize: ";
    Printer<int32_t>::stream(s, indent + "  ", v.stateSize);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "P_hat[]" << std::endl;
    for (size_t i = 0; i < v.P_hat.size(); ++i)
    {
      s << indent << "  P_hat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.P_hat[i]);
    }
    s << indent << "X_hat[]" << std::endl;
    for (size_t i = 0; i < v.X_hat.size(); ++i)
    {
      s << indent << "  X_hat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.X_hat[i]);
    }
    s << indent << "s[]" << std::endl;
    for (size_t i = 0; i < v.s.size(); ++i)
    {
      s << indent << "  s[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.s[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATION_MESSAGE_EIFPAIRSTAMPED_H
