// Generated by gencpp from file voronoi_cbsa/densityGradient.msg
// DO NOT EDIT!


#ifndef VORONOI_CBSA_MESSAGE_DENSITYGRADIENT_H
#define VORONOI_CBSA_MESSAGE_DENSITYGRADIENT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace voronoi_cbsa
{
template <class ContainerAllocator>
struct densityGradient_
{
  typedef densityGradient_<ContainerAllocator> Type;

  densityGradient_()
    : header()
    , gradient_x()
    , gradient_y()  {
    }
  densityGradient_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gradient_x(_alloc)
    , gradient_y(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _gradient_x_type;
  _gradient_x_type gradient_x;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _gradient_y_type;
  _gradient_y_type gradient_y;





  typedef boost::shared_ptr< ::voronoi_cbsa::densityGradient_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voronoi_cbsa::densityGradient_<ContainerAllocator> const> ConstPtr;

}; // struct densityGradient_

typedef ::voronoi_cbsa::densityGradient_<std::allocator<void> > densityGradient;

typedef boost::shared_ptr< ::voronoi_cbsa::densityGradient > densityGradientPtr;
typedef boost::shared_ptr< ::voronoi_cbsa::densityGradient const> densityGradientConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voronoi_cbsa::densityGradient_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voronoi_cbsa::densityGradient_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::voronoi_cbsa::densityGradient_<ContainerAllocator1> & lhs, const ::voronoi_cbsa::densityGradient_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gradient_x == rhs.gradient_x &&
    lhs.gradient_y == rhs.gradient_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::voronoi_cbsa::densityGradient_<ContainerAllocator1> & lhs, const ::voronoi_cbsa::densityGradient_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace voronoi_cbsa

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::voronoi_cbsa::densityGradient_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voronoi_cbsa::densityGradient_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_cbsa::densityGradient_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_cbsa::densityGradient_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_cbsa::densityGradient_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_cbsa::densityGradient_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voronoi_cbsa::densityGradient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbfc8681c266124a45b98ba27e25a5f7";
  }

  static const char* value(const ::voronoi_cbsa::densityGradient_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbfc8681c266124aULL;
  static const uint64_t static_value2 = 0x45b98ba27e25a5f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::voronoi_cbsa::densityGradient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voronoi_cbsa/densityGradient";
  }

  static const char* value(const ::voronoi_cbsa::densityGradient_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voronoi_cbsa::densityGradient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] gradient_x\n"
"float64[] gradient_y\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::voronoi_cbsa::densityGradient_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voronoi_cbsa::densityGradient_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gradient_x);
      stream.next(m.gradient_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct densityGradient_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voronoi_cbsa::densityGradient_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voronoi_cbsa::densityGradient_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gradient_x[]" << std::endl;
    for (size_t i = 0; i < v.gradient_x.size(); ++i)
    {
      s << indent << "  gradient_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gradient_x[i]);
    }
    s << indent << "gradient_y[]" << std::endl;
    for (size_t i = 0; i < v.gradient_y.size(); ++i)
    {
      s << indent << "  gradient_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gradient_y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VORONOI_CBSA_MESSAGE_DENSITYGRADIENT_H
