// Generated by gencpp from file voronoi_cbsa/ExchangeDataArray.msg
// DO NOT EDIT!


#ifndef VORONOI_CBSA_MESSAGE_EXCHANGEDATAARRAY_H
#define VORONOI_CBSA_MESSAGE_EXCHANGEDATAARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <voronoi_cbsa/ExchangeData.h>

namespace voronoi_cbsa
{
template <class ContainerAllocator>
struct ExchangeDataArray_
{
  typedef ExchangeDataArray_<ContainerAllocator> Type;

  ExchangeDataArray_()
    : data()  {
    }
  ExchangeDataArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::voronoi_cbsa::ExchangeData_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::voronoi_cbsa::ExchangeData_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> const> ConstPtr;

}; // struct ExchangeDataArray_

typedef ::voronoi_cbsa::ExchangeDataArray_<std::allocator<void> > ExchangeDataArray;

typedef boost::shared_ptr< ::voronoi_cbsa::ExchangeDataArray > ExchangeDataArrayPtr;
typedef boost::shared_ptr< ::voronoi_cbsa::ExchangeDataArray const> ExchangeDataArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator1> & lhs, const ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator1> & lhs, const ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace voronoi_cbsa

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d040e661939b9707099a5ae103d30bfd";
  }

  static const char* value(const ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd040e661939b9707ULL;
  static const uint64_t static_value2 = 0x099a5ae103d30bfdULL;
};

template<class ContainerAllocator>
struct DataType< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voronoi_cbsa/ExchangeDataArray";
  }

  static const char* value(const ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ExchangeData[] data\n"
"================================================================================\n"
"MSG: voronoi_cbsa/ExchangeData\n"
"int64               id\n"
"geometry_msgs/Point position\n"
"SensorArray         role\n"
"WeightArray         weights\n"
"WeightArray         sensor_scores\n"
"float64             operation_range\n"
"float64             approx_param\n"
"float64             smoke_variance\n"
"float64             camera_range\n"
"float64             angle_of_view\n"
"float64             camera_variance\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: voronoi_cbsa/SensorArray\n"
"Sensor[] sensors\n"
"================================================================================\n"
"MSG: voronoi_cbsa/Sensor\n"
"string type\n"
"float64 score\n"
"================================================================================\n"
"MSG: voronoi_cbsa/WeightArray\n"
"Weight[] weights\n"
"================================================================================\n"
"MSG: voronoi_cbsa/Weight\n"
"string  type\n"
"int16   event_id\n"
"float64 score\n"
;
  }

  static const char* value(const ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExchangeDataArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voronoi_cbsa::ExchangeDataArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::voronoi_cbsa::ExchangeData_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VORONOI_CBSA_MESSAGE_EXCHANGEDATAARRAY_H
