// Generated by gencpp from file voronoi_cbsa/NeighborInfo.msg
// DO NOT EDIT!


#ifndef VORONOI_CBSA_MESSAGE_NEIGHBORINFO_H
#define VORONOI_CBSA_MESSAGE_NEIGHBORINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <voronoi_cbsa/SensorArray.h>

namespace voronoi_cbsa
{
template <class ContainerAllocator>
struct NeighborInfo_
{
  typedef NeighborInfo_<ContainerAllocator> Type;

  NeighborInfo_()
    : id(0)
    , position()
    , role()
    , operation_range(0.0)
    , approx_param(0.0)
    , smoke_variance(0.0)
    , camera_range(0.0)
    , angle_of_view(0.0)
    , camera_variance(0.0)  {
    }
  NeighborInfo_(const ContainerAllocator& _alloc)
    : id(0)
    , position(_alloc)
    , role(_alloc)
    , operation_range(0.0)
    , approx_param(0.0)
    , smoke_variance(0.0)
    , camera_range(0.0)
    , angle_of_view(0.0)
    , camera_variance(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::voronoi_cbsa::SensorArray_<ContainerAllocator>  _role_type;
  _role_type role;

   typedef double _operation_range_type;
  _operation_range_type operation_range;

   typedef double _approx_param_type;
  _approx_param_type approx_param;

   typedef double _smoke_variance_type;
  _smoke_variance_type smoke_variance;

   typedef double _camera_range_type;
  _camera_range_type camera_range;

   typedef double _angle_of_view_type;
  _angle_of_view_type angle_of_view;

   typedef double _camera_variance_type;
  _camera_variance_type camera_variance;





  typedef boost::shared_ptr< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> const> ConstPtr;

}; // struct NeighborInfo_

typedef ::voronoi_cbsa::NeighborInfo_<std::allocator<void> > NeighborInfo;

typedef boost::shared_ptr< ::voronoi_cbsa::NeighborInfo > NeighborInfoPtr;
typedef boost::shared_ptr< ::voronoi_cbsa::NeighborInfo const> NeighborInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::voronoi_cbsa::NeighborInfo_<ContainerAllocator1> & lhs, const ::voronoi_cbsa::NeighborInfo_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position &&
    lhs.role == rhs.role &&
    lhs.operation_range == rhs.operation_range &&
    lhs.approx_param == rhs.approx_param &&
    lhs.smoke_variance == rhs.smoke_variance &&
    lhs.camera_range == rhs.camera_range &&
    lhs.angle_of_view == rhs.angle_of_view &&
    lhs.camera_variance == rhs.camera_variance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::voronoi_cbsa::NeighborInfo_<ContainerAllocator1> & lhs, const ::voronoi_cbsa::NeighborInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace voronoi_cbsa

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11f2e8ce0512f33d5dfa93d67585eb65";
  }

  static const char* value(const ::voronoi_cbsa::NeighborInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11f2e8ce0512f33dULL;
  static const uint64_t static_value2 = 0x5dfa93d67585eb65ULL;
};

template<class ContainerAllocator>
struct DataType< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voronoi_cbsa/NeighborInfo";
  }

  static const char* value(const ::voronoi_cbsa::NeighborInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"geometry_msgs/Point position\n"
"SensorArray role\n"
"float64             operation_range\n"
"float64             approx_param\n"
"float64             smoke_variance\n"
"float64             camera_range\n"
"float64             angle_of_view\n"
"float64             camera_variance\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: voronoi_cbsa/SensorArray\n"
"Sensor[] sensors\n"
"================================================================================\n"
"MSG: voronoi_cbsa/Sensor\n"
"string type\n"
"float64 score\n"
;
  }

  static const char* value(const ::voronoi_cbsa::NeighborInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.role);
      stream.next(m.operation_range);
      stream.next(m.approx_param);
      stream.next(m.smoke_variance);
      stream.next(m.camera_range);
      stream.next(m.angle_of_view);
      stream.next(m.camera_variance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NeighborInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voronoi_cbsa::NeighborInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voronoi_cbsa::NeighborInfo_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "role: ";
    s << std::endl;
    Printer< ::voronoi_cbsa::SensorArray_<ContainerAllocator> >::stream(s, indent + "  ", v.role);
    s << indent << "operation_range: ";
    Printer<double>::stream(s, indent + "  ", v.operation_range);
    s << indent << "approx_param: ";
    Printer<double>::stream(s, indent + "  ", v.approx_param);
    s << indent << "smoke_variance: ";
    Printer<double>::stream(s, indent + "  ", v.smoke_variance);
    s << indent << "camera_range: ";
    Printer<double>::stream(s, indent + "  ", v.camera_range);
    s << indent << "angle_of_view: ";
    Printer<double>::stream(s, indent + "  ", v.angle_of_view);
    s << indent << "camera_variance: ";
    Printer<double>::stream(s, indent + "  ", v.camera_variance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VORONOI_CBSA_MESSAGE_NEIGHBORINFO_H
