// Generated by gencpp from file voronoi_cbsa/Sensor.msg
// DO NOT EDIT!


#ifndef VORONOI_CBSA_MESSAGE_SENSOR_H
#define VORONOI_CBSA_MESSAGE_SENSOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voronoi_cbsa
{
template <class ContainerAllocator>
struct Sensor_
{
  typedef Sensor_<ContainerAllocator> Type;

  Sensor_()
    : type()
    , score(0.0)  {
    }
  Sensor_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , score(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef double _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::voronoi_cbsa::Sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voronoi_cbsa::Sensor_<ContainerAllocator> const> ConstPtr;

}; // struct Sensor_

typedef ::voronoi_cbsa::Sensor_<std::allocator<void> > Sensor;

typedef boost::shared_ptr< ::voronoi_cbsa::Sensor > SensorPtr;
typedef boost::shared_ptr< ::voronoi_cbsa::Sensor const> SensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voronoi_cbsa::Sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voronoi_cbsa::Sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::voronoi_cbsa::Sensor_<ContainerAllocator1> & lhs, const ::voronoi_cbsa::Sensor_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::voronoi_cbsa::Sensor_<ContainerAllocator1> & lhs, const ::voronoi_cbsa::Sensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace voronoi_cbsa

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::voronoi_cbsa::Sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voronoi_cbsa::Sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_cbsa::Sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_cbsa::Sensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_cbsa::Sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_cbsa::Sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voronoi_cbsa::Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac5a2170d45f896240e0e9487f638f4a";
  }

  static const char* value(const ::voronoi_cbsa::Sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac5a2170d45f8962ULL;
  static const uint64_t static_value2 = 0x40e0e9487f638f4aULL;
};

template<class ContainerAllocator>
struct DataType< ::voronoi_cbsa::Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voronoi_cbsa/Sensor";
  }

  static const char* value(const ::voronoi_cbsa::Sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voronoi_cbsa::Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n"
"float64 score\n"
;
  }

  static const char* value(const ::voronoi_cbsa::Sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voronoi_cbsa::Sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voronoi_cbsa::Sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voronoi_cbsa::Sensor_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "score: ";
    Printer<double>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VORONOI_CBSA_MESSAGE_SENSOR_H
